import { ConceptsArr } from "./types";
import { sortConceptsArr } from "./utils";

const project1Concepts: ConceptsArr = [
  "<script> with the `src` attribute",
  "console.log()",
  "var",
  "Initializing with a value (string, number, etc.)",
  "let",
  "camelCase",
  "const",
  "Basic string usage (single or double quotes, backticks)",
  "document.querySelector()",
  "Multi-line comments",
  "Declaring a variable without initializing it",
  "Single-line comments",
  "event.onclick",
  "Declaring a function",
  "el.innerText",
  "Escaped characters: *, \\, etc.",
  "Arguments / parameters",
  "Basic object usage ",
  "el.style",
  "Bracket notation",
  "Code lines end with a semi-colon",
  "Assignment: =",
  "invoke function",
  "Greater than or equal: >=",
  "if...else statement",
  "Less than or equal: <=",
  "Dot notation",
  "Greater than: >",
  "Concatenation",
  "Less than: <",
  "Math.floor()",
  "Subtraction assignment -=",
  "Decrement: --",
  "Less than: <",
  "Increment: ++",
  "Math.random()",
  "array",
  "Ternary operator",
  "arr.push()",
  "Compound assignment: +=",
  "arr.shift()",
  "Strict equality: ===",
  "arr.length",
  "Strict inequality: !==",
  "arr.pop()",
  "Logical AND: &&",
  "arr.indexOf()",
  "Logical OR: ||",
  "while loop",
  "return statement",
  "for loop",
];

export const rpgGameConcepts = sortConceptsArr(project1Concepts);

export const calorieCounter: ConceptsArr = [
  "const",
  "Assignment: =",
  "let",
  "Compound assignment: +=",
  "document.getElementById()",
  "boolean",
  "document.querySelector()",
  "Declaring a function",
  "document.querySelectorAll()",
  "Template literal",
  "return statement",
  "Arguments / parameters",
  "str.replace()",
  "arr.length",
  "str.match()",
  "Global flag: g",
  "str.toLowerCase()",
  "insertAdjacentHTML",
  "Case insensitivity flag: i",
  "Bracket notation",
  "event.preventDefault()",
  "Dot notation",
  "Character class / set: [...]",
  "Concatenation",
  "Match any digit: d",
  "el.innerHTML",
  "Quantifier: + (matches the preceding item 1 or more times)",
  "el.innerText",
  "Math.abs()",
  "el.classList",
  "Number()",
  "el.remove()",
  "for loop",
  "el.value",
  "if statement",
  "alert",
  "null",
  "Array.from()",
  "Increment: ++",
  "el.addEventListener()",
  "click",
  "submit",
];

export const musicPlayer: ConceptsArr = [];
export const dateFormatter: ConceptsArr = [
  "const",
  "document.getElementById()",
  "Assignment: =",
  "new Date()",
  "date.getDate()",
  "date.getMonth()",
  "date.getFullYear()",
  "date.getHours()",
  "date.getMinutes()",
  "Intl.DateTimeFormat",
  "Template literal",
  "el.textContent",
  "el.addEventListener()",
  "change",
  "el.value",
  "switch",
  "Basic string usage (single or double quotes, backticks)",
  "str.split()",
  "arr.reverse()",
  "arr.join()",
  "Basic object usage ",
];

export const palindromeChecker: ConceptsArr = [
  "const",
  "document.getElementById()",
  "let",
  "Basic string usage (single or double quotes, backticks)",
  "alert",
  "Arrow function",
  "if statement",
  "Strict equality: ===",
  "Arguments / parameters",
  "return statement",
  "str.replace()",
  "Global flag: g",
  "Case insensitivity flag: i",
  "str.toLowerCase()",
  "Character class / set: [...]",
  "Match characters in a range: a-z, 0-9, etc.",
  "Template literal",
  "Spread syntax: ...",
  "arr.reverse()",
  "el.appendChild()",
  "el.createTextNode()",
  "arr.join()",
  "el.className",
  "Ternary operator",
  "document.createElement()",
  "click",
  "el.classList",
  "el.addEventListener()",
];

export const footballTeamCards: ConceptsArr = [
  "const",
  "document.getElementById()",
  "Assignment: =",
  "Basic string usage (single or double quotes, backticks)",
  "Basic object usage ",
  "boolean",
  "Object.freeze()",
  "Dot notation",
  "Destructuring assignment",
  "el.innerHTML",
  "Default parameters",
  "Arrow function",
  "arr.map()",
  "Template literal",
  "arr.filter()",
  "Compound assignment: +=",
  "Ternary operator",
  "Strict inequality: !==",
  "null",
  "Strict equality: ===",
  "change",
  "el.addEventListener()",
  "el.value",
  "switch",
  "invoke function",
];

export const todoListApp: ConceptsArr = [];
export const recursionProject: ConceptsArr = [
  "const",
  "document.getElementById()",
  "array",
  "Basic object usage ",
  "Arrow function",
  "Basic string usage (single or double quotes, backticks)",
  "el.textContent",
  "el.style",
  "arr.map()",
  "settimeout()",
  "Template literal",
  "el.innerHTML",
  "el.remove()",
  "if...else statement",
  "return statement",
  "Strict equality: ===",
  "Math.floor()",
  "parseInt()",
  "el.addEventListener()",
  "Remainder / modulo: %",
  "click",
  "keydown",
  "alert",
  "event.key",
];
export const romanNumeralConverter: ConceptsArr = [];
export const numberSorter: ConceptsArr = [
  "const",
  "document.getElementById()",
  "let",
  "document.getElementsByClassName()",
  "arr.map()",
  "Arrow function",
  "event.preventDefault()",
  "array",
  "Number()",
  "el.value",
  "Spread syntax: ...",
  "arr.sort()",
  "arr.forEach()",
  "Template literal",
  "el.innerText",
  "Arguments / parameters",
  "Assignment: =",
  "for loop",
  "Increment: ++",
  "while loop",
  "Decrement: --",
  "arr.length",
  "Greater than: >",
  "return statement",
  "Greater than or equal: >=",
  "click",
  "el.addEventListener()",
];
export const statsCalculator: ConceptsArr = [
  "Arrow function",
  "Arguments / parameters",
  "arr.reduce()",
  "arr.length",
  "arr.slice()",
  "Remainder / modulo: %",
  "arr.sort()",
  "Strict equality: ===",
  "Bracket notation",
  "Math.floor()",
  "return statement",
  "Math.max()",
  "Ternary operator",
  "Math.min()",
  "Basic object usage ",
  "Math.sqrt()",
  "arr.forEach()",
  "Logical OR: ||",
  "arr.filter()",
  "new Set()",
  "arr.join()",
  "if statement",
  "arr.map()",
  "null",
  "Object.values()",
  "Set().size",
  "Object.keys()",
  "Spread syntax: ...",
  "Exponentiation: **",
  "document.querySelector()",
  "const",
  "getElementsByTagName",
  "el.value",
  "str.split()",
  "Global flag: g",
  "Number()",
  "Logical NOT: !",
  "isNan()",
  "el.textContent",
  "Assignment: =",
  "Bracket notation",
  "el.addEventListener()",
  "submit",
  "event.preventDefault()",
];
export const spreadsheetProject: ConceptsArr = [];
export const spamFilter: ConceptsArr = [
  "const",
  "document.getElementById()",
  "Match characters in a range: a-z, 0-9, etc.",
  "array",
  "Case insensitivity flag: i",
  "Assignment: =",
  "Global flag: g",
  "Arrow function",
  "Arguments / parameters",
  "arr.some()",
  "regex.test()",
  "boolean",
  "el.addEventListener()",
  "click",
  "if statement",
  "alert",
  "Strict equality: ===",
  "Basic string usage (single or double quotes, backticks)",
  "return statement",
  "Ternary operator",
  "el.textContent",
];
export const telephoneValidator: ConceptsArr = [];
export const shoppingCart: ConceptsArr = [
  "const",
  "document.getElementById()",
  "let",
  "document.getElementsByClassName()",
  "Assignment: =",
  "array",
  "Strict equality: ===",
  "arr.map()",
  "Basic object usage ",
  "arr.find()",
  "Basic string usage (single or double quotes, backticks)",
  "arr.forEach()",
  "Destructuring assignment",
  "arr.reduce()",
  "el.innerHTML",
  "Template literal",
  "el.textContent",
  "Arrow function",
  "class ClassName / new ClassName()",
  "this",
  "Logical OR: ||",
  "Dot notation",
  "Bracket notation",
  "Concatenation",
  "Ternary operator",
  "return statement",
  "arr.length",
  "alert",
  "if statement",
  "confirm",
  "parseFloat()",
  "num.toFixed()",
  "Spread syntax: ...",
  "el.addEventListener()",
  "click",
  "el.style",
  "Logical NOT: !",
];
export const platformerGamer: ConceptsArr = [];
export const diceGame: ConceptsArr = [];
export const cashRegister: ConceptsArr = [];
export const fccAuthorsPage: ConceptsArr = [
  "const",
  "document.getElementById()",
  "let",
  "Assignment: =",
  "array",
  "Basic string usage (single or double quotes, backticks)",
  "fetch()",
  "res.json()",
  "arr.slice()",
  "el.innerHTML",
  "Template literal",
  "console.error",
  "Arrow function",
  "Compound assignment: +=",
  "if statement",
  "Less than or equal: <=",
  "boolean",
  "el.textContent",
  "el.disabled",
  "Arguments / parameters",
  "arr.forEach()",
  "Destructuring assignment",
  "el.addEventListener()",
  "click",
];
export const fccForumLeaderboard: ConceptsArr = [];
export const randomQuoteMachine: ConceptsArr = [];
