import { ConceptsArr } from "./pages/types";

export const rpgGameConcepts: ConceptsArr = [
  "<script> with the `src` attribute",
  "console.log()",
  "var",
  "Initializing with a value (string, number, etc.)",
  "let",
  "camelCase",
  "const",
  "Basic string usage (single or double quotes, backticks)",
  "document.querySelector()",
  "Multi-line comments",
  "Declaring a variable without initializing it",
  "Single-line comments",
  "event.onclick",
  "Declaring a function",
  "el.innerText",
  "Escaped characters: *, \\, etc.",
  "Arguments / parameters",
  "Basic object usage ",
  "el.style",
  "Bracket notation",
  "Code lines end with a semi-colon",
  "Assignment: =",
  "invoke function",
  "Greater than or equal: >=",
  "if...else statement",
  "Less than or equal: <=",
  "Dot notation",
  "Greater than: >",
  "Concatenation",
  "Less than: <",
  "Math.floor()",
  "Subtraction assignment -=",
  "Decrement: --",
  "Less than: <",
  "Increment: ++",
  "Math.random()",
  "array",
  "Ternary operator",
  "arr.push()",
  "Compound assignment: +=",
  "arr.shift()",
  "Strict equality: ===",
  "arr.length",
  "Strict inequality: !==",
  "arr.pop()",
  "Logical AND: &&",
  "arr.indexOf()",
  "Logical OR: ||",
  "while loop",
  "return statement",
  "for loop",
];

export const calorieCounter: ConceptsArr = [
  "const",
  "Assignment: =",
  "let",
  "Compound assignment: +=",
  "document.getElementById()",
  "boolean",
  "document.querySelector()",
  "Declaring a function",
  "document.querySelectorAll()",
  "Template literal",
  "return statement",
  "Arguments / parameters",
  "str.replace()",
  "arr.length",
  "str.match()",
  "Global flag: g",
  "str.toLowerCase()",
  "insertAdjacentHTML",
  "Case insensitivity flag: i",
  "Bracket notation",
  "event.preventDefault()",
  "Dot notation",
  "Character class / set: [...]",
  "Concatenation",
  "Match any digit: d",
  "el.innerHTML",
  "Quantifier: + (matches the preceding item 1 or more times)",
  "el.innerText",
  "Math.abs()",
  "el.classList",
  "Number()",
  "el.remove()",
  "for loop",
  "el.value",
  "if statement",
  "alert",
  "null",
  "Array.from()",
  "Increment: ++",
  "el.addEventListener()",
  "click",
  "submit",
];

export const musicPlayer: ConceptsArr = [];
export const dateFormatter: ConceptsArr = [
  "const",
  "document.getElementById()",
  "Assignment: =",
  "new Date()",
  "date.getDate()",
  "date.getMonth()",
  "date.getFullYear()",
  "date.getHours()",
  "date.getMinutes()",
  "Intl.DateTimeFormat",
  "Template literal",
  "el.textContent",
  "el.addEventListener()",
  "change",
  "el.value",
  "switch",
  "Basic string usage (single or double quotes, backticks)",
  "str.split()",
  "arr.reverse()",
  "arr.join()",
  "Basic object usage ",
];
